Imports MongoDB.Bson
Imports MongoDB.Bson.Serialization.Attributes

Public Class KeyValueWithId
    <BsonId>
    <BsonRepresentation(BsonType.ObjectId)>
    Public Property Id As ObjectId 'generated by MongoDB
    Public Property Key As String
    Public Property Value As String
End Class
